name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devops-cicd-demo .

      - name: Test Docker image
        run: |
          docker run -d --name test-container -p 8080:80 devops-cicd-demo
          sleep 5
          docker ps
          docker stop test-container